# ============================================
# TestApp Kubernetes Service Account
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: testapp
  namespace: testapp
  labels:
    app: testapp
automountServiceAccountToken: false
